"""instrumento

Revision ID: 160033a39d59
Revises: 
Create Date: 2026-06-14 10:49:34.193960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '160033a39d59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrumento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_interno', sa.String(), nullable=True),
    sa.Column('serial', sa.String(), nullable=True),
    sa.Column('equipamento', sa.String(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('faixa', sa.String(), nullable=True),
    sa.Column('unidade_faixa', sa.String(), nullable=True),
    sa.Column('disciplina', sa.Enum('ELE', 'MEC', name='disciplina'), nullable=True),
    sa.Column('sistema', sa.String(), nullable=True),
    sa.Column('ciclo_meses', sa.Integer(), nullable=False),
    sa.Column('data_ultima_calibracao', sa.Date(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('flag_origem', sa.String(), nullable=True),
    sa.Column('organizacao_calibradora', sa.String(), nullable=True),
    sa.Column('local_calibracao', sa.String(), nullable=True),
    sa.Column('custo_estimado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('custo_contratado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('certificado_ref', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrumento_codigo_interno'), 'instrumento', ['codigo_interno'], unique=False)
    op.create_index(op.f('ix_instrumento_serial'), 'instrumento', ['serial'], unique=False)
    op.create_index(op.f('ix_instrumento_sistema'), 'instrumento', ['sistema'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instrumento_sistema'), table_name='instrumento')
    op.drop_index(op.f('ix_instrumento_serial'), table_name='instrumento')
    op.drop_index(op.f('ix_instrumento_codigo_interno'), table_name='instrumento')
    op.drop_table('instrumento')
    # ### end Alembic commands ###
