"""base metrologica

Revision ID: c00a5e8ec52e
Revises: 160033a39d59
Create Date: 2026-06-14 13:24:25.908815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00a5e8ec52e'
down_revision: Union[str, Sequence[str], None] = '160033a39d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('familia_metrologica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('unidade_medida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('simbolo', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('grandeza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=True),
    sa.Column('unidade_padrao_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['familia_id'], ['familia_metrologica.id'], ),
    sa.ForeignKeyConstraint(['unidade_padrao_id'], ['unidade_medida.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipo_instrumento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['familia_id'], ['familia_metrologica.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.add_column('instrumento', sa.Column('codigo_patrimonial', sa.String(), nullable=True))
    op.add_column('instrumento', sa.Column('faixa_min', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('instrumento', sa.Column('faixa_max', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('instrumento', sa.Column('resolucao', sa.String(), nullable=True))
    op.add_column('instrumento', sa.Column('emp', sa.String(), nullable=True))
    op.add_column('instrumento', sa.Column('familia_id', sa.Integer(), nullable=True))
    op.add_column('instrumento', sa.Column('tipo_id', sa.Integer(), nullable=True))
    op.add_column('instrumento', sa.Column('grandeza_id', sa.Integer(), nullable=True))
    op.add_column('instrumento', sa.Column('unidade_id', sa.Integer(), nullable=True))
    op.add_column('instrumento', sa.Column('organizacao', sa.String(), nullable=True))
    op.add_column('instrumento', sa.Column('unidade_org', sa.String(), nullable=True))
    op.add_column('instrumento', sa.Column('secao', sa.String(), nullable=True))
    op.add_column('instrumento', sa.Column('bancada', sa.String(), nullable=True))
    op.add_column('instrumento', sa.Column('status_operacional', sa.Enum('ATIVO', 'EM_CALIBRACAO', 'EM_MANUTENCAO', 'REPROVADO', 'BLOQUEADO', 'BAIXADO', name='statusoperacional'), nullable=False, server_default='ATIVO'))
    op.add_column('instrumento', sa.Column('foto_path', sa.String(), nullable=True))
    op.add_column('instrumento', sa.Column('manual_path', sa.String(), nullable=True))
    op.add_column('instrumento', sa.Column('fu', sa.Integer(), nullable=True))
    op.add_column('instrumento', sa.Column('nc', sa.Integer(), nullable=True))
    op.add_column('instrumento', sa.Column('ab', sa.Integer(), nullable=True))
    op.add_column('instrumento', sa.Column('cm', sa.Integer(), nullable=True))
    op.add_column('instrumento', sa.Column('ci', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_instrumento_codigo_patrimonial'), 'instrumento', ['codigo_patrimonial'], unique=False)
    # NOTE: as foreign keys de instrumento (tipo_id, unidade_id, familia_id,
    # grandeza_id) NAO sao adicionadas aqui: o SQLite nao suporta ALTER TABLE
    # ADD CONSTRAINT e fazer isso exigiria reconstruir a tabela (batch mode),
    # arriscando os ~496 registros existentes. As colunas FK ficam como
    # inteiros simples; os relacionamentos ORM continuam funcionando.
    # ### end Alembic commands ###
    op.create_index(
        "uq_instrumento_codigo_patrimonial",
        "instrumento",
        ["codigo_patrimonial"],
        unique=True,
        sqlite_where=sa.text("codigo_patrimonial IS NOT NULL"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("uq_instrumento_codigo_patrimonial", table_name="instrumento")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instrumento_codigo_patrimonial'), table_name='instrumento')
    op.drop_column('instrumento', 'ci')
    op.drop_column('instrumento', 'cm')
    op.drop_column('instrumento', 'ab')
    op.drop_column('instrumento', 'nc')
    op.drop_column('instrumento', 'fu')
    op.drop_column('instrumento', 'manual_path')
    op.drop_column('instrumento', 'foto_path')
    op.drop_column('instrumento', 'status_operacional')
    op.drop_column('instrumento', 'bancada')
    op.drop_column('instrumento', 'secao')
    op.drop_column('instrumento', 'unidade_org')
    op.drop_column('instrumento', 'organizacao')
    op.drop_column('instrumento', 'unidade_id')
    op.drop_column('instrumento', 'grandeza_id')
    op.drop_column('instrumento', 'tipo_id')
    op.drop_column('instrumento', 'familia_id')
    op.drop_column('instrumento', 'emp')
    op.drop_column('instrumento', 'resolucao')
    op.drop_column('instrumento', 'faixa_max')
    op.drop_column('instrumento', 'faixa_min')
    op.drop_column('instrumento', 'codigo_patrimonial')
    op.drop_table('tipo_instrumento')
    op.drop_table('grandeza')
    op.drop_table('unidade_medida')
    op.drop_table('familia_metrologica')
    # ### end Alembic commands ###
